dist: trusty
language: node_js
node_js:
- "8"
cache:
  directories:
  - node_modules
  - ~/.cache
before_script:
- npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &
script:
- npx cypress run  --spec cypress/integration/expendituresup.spec.js
deploy:
  provider: surge
  skip_cleanup: true
  domain: exotic-advice.surge.sh
  project: ./dist
  on:
    branch: master
